### PR TITLE
Relax/dedup version bounds and build on LTS 18.0

### PR DESCRIPTION
**Pull request by thomasjm**
I haven't tested it yet, but these tweaks make it build successfully on LTS 18 (GHC 8.10.4).

### CODE REVIEW

**Comment by kuribas** [comment]
It's not a great idea to simply remove all version  checks.  Each package should have a upper and lower version bound.  We can move the upper version bound up.

**Comment by thomasjm** [comment]
> It's not a great idea to simply remove all version checks.

I didn't remove them all. But I think it's actually preferable to do so these days when you make ordinary use of common packages such as `text`, `containers`, etc. which are quite stable. When you're using a resolver like Stackage, you already know all the packages build with each other. If your package builds too, then it probably works. I've found that this tends to be more future-proof and avoids the need to constantly bump the bounds to keep things working.

One exception is when some dependency contains a change that actually matters at some version, which you can enforce with a version bound, or even better with a CPP if statement. Another exception is for less common dependencies which may be less carefully versioned. (I left some bounds in for those.)

For example, you can see that `aeson-diff` follows this philosophy: https://github.com/thsutton/aeson-diff/blob/master/aeson-diff.cabal

**Comment by kuribas** [comment]
Please read https://pvp.haskell.org/ , in particular the section "Dependencies in Cabal".  There is a good reason people write these documents you know!  Just because some packages choose to use their own scheme, or to be just sloppy, doesn't mean we have to follow.  If you need to relax upper bounds, just move them up, not remove them completely.

**Comment by thomasjm** [comment]
Well, at the moment I'm thinking I won't be able to use this library anyway because I started hitting bugs. What do you think about the two I filed? Curious if I'm missing something/how much work you think it might be to fix these cases.

**Comment by kuribas** [comment]
I haven't had time to look at those, sorry...

**Comment by thomasjm** [comment]
No worries -- feel free to close this PR if you like. I'm probably going to use raw `aeson-diff` until this library has something resembling a test suite :P. Thanks for the fast responses.

**Pull request closed without merging**
